### PR TITLE
Convert colors to use `hsl`/`hsla`

### PR DESCRIPTION
**Pull request by FichteFoll**
It's more convenient to modify these and they feel more natural to the
human mind.

Numbers were slightly rounded after conversion for convenience with
barely noticeable changes.

I know you disagreed on this change, so I made sure to do this in its own PR.

### CODE REVIEW

**Comment by Ennea** [comment]
Yea, I'm closing this one. Rounding colors is heresy 😋 They also don't need to be readable or intuitively understandable either.

**Comment by FichteFoll** [comment]
> Rounding colors is heresy

Got any sources on how that actually affects things or is it just out of principle?

**Comment by Ennea** [comment]
It's just principle. I picked those colors in LCH color space. They're represented in sRGB space in the stylesheet because that's the "default" and they don't need to be readable anyway, as I said, since they aren't code. Converting them to HSL and then _rounding_ them just seems nonsensical.

**Comment by FichteFoll** [comment]
Why not use [`lch()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lch) [directly](https://caniuse.com/css-lch-lab), then?

**Comment by Ennea** [comment]
Support for that is still a tad too recent for my taste.

**Pull request closed without merging**
