### PR TITLE
Better compatibility with custom game paths

### PR DESCRIPTION
**Pull request by jericjan**
I installed the game using neon-nyan's [Collapse launcher](https://github.com/neon-nyan/Collapse). It installed the game for me without having the "Game" folder so a line in Player.log looks like this:
`Loading player data from F:/HSR/StarRail_Data/data.unity3d`

So I modified the regex so that it would also detect this. It should still work even if you do have the "Game" folder in the path.

### CODE REVIEW

**Comment by Ennea** [comment]
`util.py` changed in #1, so this needs updating. If you could also adjust the `GAME_PATH` path in the Linux instructions in the readme, that would be great.

**Comment by FichteFoll** [comment]
I also made this change as a part of https://github.com/FichteForks/warp-journal/commit/baac8c104b359dab70db55589ebf3562e9fb4e2d, which I was waiting on #1 to be merged before I filed a PR for it.

**Comment by FichteFoll** [comment]
Does the Collapse launcher have a way of finding/identifying its install location and/or the install location of HSR? That way we could add automatic detection for it.

**Comment by jericjan** [comment]
Well, there is a file in `%USERPROFILE%\AppData\LocalLow\CollapseLauncher\GameFolder\SRGlb\config.ini` which contains `game_install_path=F:/HSR` for me. Why bother with this though? Won't the regex filter work fine regardless?

**Comment by FichteFoll** [comment]
Ah right, it already reads the game path from the logs in `%USERPROFILE%`, so never mind.

**Pull request closed without merging**
