### PR TITLE
Add "Warp №" column

### PR DESCRIPTION
**Pull request by FichteFoll**

### CODE REVIEW

**Comment by Ennea** [comment]
What exactly is the purpose of this column? I've tried keeping the available columns to a minimum, only including data that is useful. What's the use case for incrementing a counter from the very first gacha pull?

**Comment by FichteFoll** [comment]
It's the only way to find out how many pulls you have made on a banner in total. The full total count is displayed above the table but includes *all* wishes from all banners, whereas I found it somewhat interesting to also be able to track where I currently stand in a banner without only looking at the "current pity" table, which I honestly don't find easy to navigate visually at the moment.

Of course, changing the "current pity" table would also be a viable alternative, but including the warp number (per banner) accomplishes more for now. Alternatively, the column could be made redundant if all the information you could extract from it (number of pulls, current pity) could be extracted more easily on a per-banner bases like on paimon.moe, for example, but that would be a much more involved change because it affects the current behavior of merging all wishes inside a single table on a fundamental level (which I don't think is useful btw) since the individual banners should stand on their own, but again, that change would be more involved.

<details>
<summary>Screenshots for easier understanding of what I'm talking about</summary>

image



</details>

**Comment by FichteFoll** [comment]
Interestingly, paimon.moe also has the wish counter per banner when you open the detailed screen of a banner type, but resets the counter *on banner change* as well. I suppose that would be more useful overall to be able to track how much you pulled on one banner in particular, but would be out of scope for this project because I doubt anyone is interested in maintaining the rate-up pulls for each banner. At least I'm not.

<details>

image

</details>

**Comment by Ennea** [comment]
I agree that the "current pity" table is a bit difficult to parse right now. I had reversed the columns and rows back when I was developing Wishing Well for Genshin, because only having three columns over the entire width of the application looked really off.

Let's kill two birds with one stone here and re-design/replace the "current pity" table with something better that also gives an overview over pulls per banner. I'll spend some time on this and keep you updated.

**Comment by FichteFoll** [comment]
> Let's kill two birds with one stone here and re-design/replace the "current pity" table with something better that also gives an overview over pulls per banner.

Since that is out of scope for this PR, I'm merging this.

**Pull request merged**
