### PR TITLE
Bump greenlet to ^3.0.0

### PR DESCRIPTION
**Pull request by korewaChino**
This fixes a build error on Fedora Linux

P.S It also got me Topaz somehow, good karma i guess

### CODE REVIEW

**Comment by FichteFoll** [comment]
The most relevant change I observe appears to be [compatibility with Python 3.12](https://github.com/python-greenlet/greenlet/blob/4418940827246bfadccc256ecd3c1107a5c535a8/CHANGES.rst#L116), which is definitely needed. I assume Fedora (Rawhide) has switched to 3.12 by now, then.

**Comment by FichteFoll** [comment]
On a somewhat related note, could you share whether there is any difference in the JSON between the two character event banners? I don't want to pull myself currently …

**Comment by FichteFoll** [comment]
Thanks for the update. Meanwhile I have found out that the buttons didn't work properly and committed some fixes as well.

**Comment by korewaChino** [comment]
> The most relevant change I observe appears to be [compatibility with Python 3.12](https://github.com/python-greenlet/greenlet/blob/4418940827246bfadccc256ecd3c1107a5c535a8/CHANGES.rst#L116), which is definitely needed. I assume Fedora (Rawhide) has switched to 3.12 by now, then.

Fedora 38 and 39 uses Python 3.12 now.

**Pull request merged**
